INSERT INTO tb_users (txt_nome, txt_sobrenome, txt_email, bcr_password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_users (txt_nome, txt_sobrenome, txt_email, bcr_password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_roles (txt_authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_roles (txt_authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (oid_user, oid_role) VALUES (1, 1);
INSERT INTO tb_user_role (oid_user, oid_role) VALUES (2, 1);
INSERT INTO tb_user_role (oid_user, oid_role) VALUES (2, 2);

INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Drama', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Historia', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Comédia', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Aventura', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Fantasia', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Ação', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Ficção', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Mistério', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Thriller', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Crime', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Animação', NOW(), NOW());
INSERT INTO tb_categorias (txt_nome, dat_criacao, dat_atualizacao) VALUES ('Terror', NOW(), NOW());

INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('A milhões de quilômetros', 123, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gve64tTbxgo5NErRkwKeMdlHt5o.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('Barbie', 112, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yRRuLt7sMBEQkHsd1S3KaaofZn7.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('Besouro azul', 127, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/y5sdkgO4IJMTnkjh9PG7kREPWrP.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('A chamada', 91, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yd0iEtqAXseXQgKf9RjmMaPjUPG.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('Mercenários 4', 103, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/dQxlUkhKGILgq9jbVEe3WPaiW2q.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('As Tartarugas Ninjas: Caos Mutante', 100, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gwrFZLMPox82lsPT8MHpAYmFjw9.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('A milhões de quilômetros', 123, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gve64tTbxgo5NErRkwKeMdlHt5o.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('Barbie', 112, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yRRuLt7sMBEQkHsd1S3KaaofZn7.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('Besouro azul', 127, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/y5sdkgO4IJMTnkjh9PG7kREPWrP.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('A chamada', 91, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yd0iEtqAXseXQgKf9RjmMaPjUPG.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('Mercenários 4', 103, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/dQxlUkhKGILgq9jbVEe3WPaiW2q.jpg');
INSERT INTO tb_filmes (txt_titulo, num_duracao, num_ano_lancamento, txt_sinopse, txt_capa_url) VALUES ('As Tartarugas Ninjas: Caos Mutante', 100, 2023, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gwrFZLMPox82lsPT8MHpAYmFjw9.jpg');

INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (1, 1);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (1, 2);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (2, 3);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (2, 4);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (2, 5);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (3, 6);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (3, 7);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (3, 4);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (4, 6);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (4, 8);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (4, 9);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (4, 10);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (5, 6);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (5, 4);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (5, 9);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (6, 11);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (6, 3);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (6, 6);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (7, 1);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (7, 2);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (8, 3);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (8, 4);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (8, 5);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (9, 6);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (9, 7);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (9, 4);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (10, 6);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (10, 8);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (10, 9);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (10, 10);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (11, 6);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (11, 4);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (11, 9);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (12, 11);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (12, 3);
INSERT INTO tb_filme_categoria (oid_filme, oid_categoria) VALUES (12, 6);
